language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ree
before_script:
  - secure: "R/AC4kBD2IMCqWjIsSjNtlIGxINnFE6eckCbvpUJxEg31TU6Vajd9np/anwxe5iLbiNqbVi/EOEBULx54EdofFFuKuffYZUhG1k1arHCPJ/bCrDuN6RqYlxLmPppS9A3BaxYCr7Hrk7ZLcyvzBA7GnQis8vF4pwIE369uvj1lg0="
  - secure: "NRixf81XvESlaOYoODzf20Ewgtx2/6uJhB1HCsoOH6XgXo80jBg6xp9s1YZRMiBUYnNRQaV6PCWZ/DAWeN01bgaksHcE+mprFYEsukJpkUotamBb+XazPZAWAIi5UBpEFyD5UtnfwgkAZcEe7iUNn8w8ySIPBayE9GRpnN4zsXA="
