language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ree
env:
  - secure: "LfXCEEnHNUOCCo4eat/XA+CZvj4Uchi+j4NAuJs14MEASEj8t4t9fU8cQd/tux93iEpNgVL1C6JiWGYu7T+Hs/nzagKFuLw+gfCdwUm1FKa1CH/GQw4fcOcY1sPSaTeL6Ocm1LEPTlR3wWrbu89zIyXakklSPYl0bCArLVH/82o="
